fix: ansible 9 requires python 3.10
as seen in CI run from last commit:
```
ERROR: Ignored the following yanked versions: 9.0.0
ERROR: Ignored the following versions that require a different python version: 24.2.0 Requires-Python >=3.10; 9.0.1 Requires-Python >=3.10; 9.1.0 Requires-Python >=3.10; 9.2.0 Requires-Python >=3.10
```

and on left sidebar here: https://pypi.org/project/ansible/9.0.1/