fix(ci): remove galaxy_info.standalone
fails now for some reason i don't want to dive into (property still exists in yaml schema). hopefully this fixes it and release workflow just automatically recognizes its standalone:

https://github.com/JonasPammer/ansible-role-bootstrap/actions/runs/7949084295/job/21700271632
```
===== LOADING ROLE =====
Importing with galaxy-importer 0.4.19
Role loading failed! unknown field in galaxy_info: LegacyGalaxyInfo.__init__() got an unexpected keyword argument 'standalone'
Traceback (most recent call last):
  File "/venv/lib64/python3.11/site-packages/galaxy_importer/schema.py", line 532, in parse
    galaxy_info = LegacyGalaxyInfo(**metadata["galaxy_info"])
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: LegacyGalaxyInfo.__init__() got an unexpected keyword argument 'standalone'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "/app/galaxy_ng/app/api/v1/tasks.py", line 427, in legacy_role_import
    result = import_legacy_role(checkout_path, namespace.name, importer_config, logger)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib64/python3.11/site-packages/galaxy_importer/legacy_role.py", line 51, in import_legacy_role
    return _import_legacy_role(dirname, namespace, cfg, logger)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib64/python3.11/site-packages/galaxy_importer/legacy_role.py", line 57, in _import_legacy_role
    data = LegacyRoleLoader(dirname, namespace, cfg, logger).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib64/python3.11/site-packages/galaxy_importer/loaders/legacy_role.py", line 41, in load
    self.metadata = self._load_metadata()
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib64/python3.11/site-packages/galaxy_importer/loaders/legacy_role.py", line 77, in _load_metadata
    return schema.LegacyMetadata.parse(meta_path)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/venv/lib64/python3.11/site-packages/galaxy_importer/schema.py", line 534, in parse
    raise exc.LegacyRoleSchemaError(f"unknown field in galaxy_info: {e}") from e
galaxy_importer.exceptions.LegacyRoleSchemaError: unknown field in galaxy_info: LegacyGalaxyInfo.__init__() got an unexpected keyword argument 'standalone'
```